from django.db import models

class Filter(models.Model):
    filter_type = models.CharField(max_length=100)
    min_price = models.CharField(max_length=100, null=True, blank=True)
    max_price = models.CharField(max_length=100, null=True, blank=True)
    tick_size = models.CharField(max_length=100, null=True, blank=True)
    step_size = models.CharField(max_length=100, null=True, blank=True)
    min_qty = models.CharField(max_length=100, null=True, blank=True)
    max_qty = models.CharField(max_length=100, null=True, blank=True)
    limit = models.CharField(max_length=100, null=True, blank=True)
    notional = models.CharField(max_length=100, null=True, blank=True)
    multiplier_up = models.CharField(max_length=100, null=True, blank=True)
    multiplier_down = models.CharField(max_length=100, null=True, blank=True)
    multiplier_decimal = models.IntegerField(null=True, blank=True)

class Symbol(models.Model):
    symbol = models.CharField(max_length=100, unique=True)
    pair = models.CharField(max_length=100)
    contract_type = models.CharField(max_length=100)
    delivery_date = models.BigIntegerField()
    onboard_date = models.BigIntegerField()
    status = models.CharField(max_length=100)
    maint_margin_percent = models.CharField(max_length=100)
    required_margin_percent = models.CharField(max_length=100)
    base_asset = models.CharField(max_length=100)
    quote_asset = models.CharField(max_length=100)
    margin_asset = models.CharField(max_length=100)
    price_precision = models.IntegerField()
    quantity_precision = models.IntegerField()
    base_asset_precision = models.IntegerField()
    quote_precision = models.IntegerField()
    underlying_type = models.CharField(max_length=100, null=True, blank=True)
    underlying_sub_type = models.JSONField(null=True, blank=True)
    settle_plan = models.IntegerField(null=True, blank=True)
    trigger_protect = models.CharField(max_length=100, null=True, blank=True)
    liquidation_fee = models.CharField(max_length=100, null=True, blank=True)
    market_take_bound = models.CharField(max_length=100, null=True, blank=True)
    max_move_order_limit = models.IntegerField(null=True, blank=True)
    filters = models.ManyToManyField(Filter)
    order_types = models.JSONField()
    time_in_force = models.JSONField()