# Generated by Django 4.1.13 on 2024-08-27 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='nunknown', max_length=100)),
                ('description', models.TextField(default='unknown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='proxy', max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('baseAsset', models.CharField(max_length=50)),
                ('baseAssetPrecision', models.IntegerField()),
                ('quoteAsset', models.CharField(max_length=50)),
                ('quotePrecision', models.IntegerField()),
                ('quoteAssetPrecision', models.IntegerField()),
                ('baseCommissionPrecision', models.IntegerField()),
                ('quoteCommissionPrecision', models.IntegerField()),
                ('orderTypes', models.JSONField()),
                ('isSpotTradingAllowed', models.BooleanField()),
                ('isMarginTradingAllowed', models.BooleanField()),
                ('quoteAmountPrecision', models.CharField(max_length=50)),
                ('baseSizePrecision', models.CharField(max_length=50)),
                ('permissions', models.JSONField()),
                ('filters', models.JSONField(blank=True, default=list)),
                ('maxQuoteAmount', models.CharField(max_length=100)),
                ('makerCommission', models.CharField(max_length=50)),
                ('takerCommission', models.CharField(max_length=50)),
                ('quoteAmountPrecisionMarket', models.CharField(max_length=100)),
                ('maxQuoteAmountMarket', models.CharField(max_length=100)),
                ('fullName', models.CharField(max_length=100)),
                ('tradeSideType', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SymbolsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_new', models.IntegerField(default=0)),
                ('time_spent', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymbolError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbols_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_error', to='s_mexc.symbolsinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_class', models.CharField(blank=True, max_length=10, null=True)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('probabilities', models.JSONField(blank=True, null=True)),
                ('up_date', models.DateTimeField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='s_mexc.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('proxy_active', models.BooleanField(default=False)),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='s_mexc.proxy')),
                ('symbols', models.ManyToManyField(to='s_mexc.symbol')),
            ],
        ),
    ]
