# Generated by Django 4.1.13 on 2024-08-28 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_mexc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='symbols',
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroup', to='s_mexc.group')),
            ],
        ),
    ]
