# Generated by Django 4.1.13 on 2024-08-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_mexc', '0002_remove_group_symbols_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='symbols',
            field=models.ManyToManyField(to='s_mexc.symbol'),
        ),
    ]
