# Generated by Django 4.1.13 on 2024-07-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_binance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='symbols',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.RemoveField(
            model_name='symbolerror',
            name='symbols_info',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Symbol',
        ),
        migrations.DeleteModel(
            name='SymbolError',
        ),
        migrations.DeleteModel(
            name='SymbolsInfo',
        ),
    ]
