# Generated by Django 4.1.13 on 2024-07-26 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s_binance', '0002_remove_group_symbols_delete_log_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='nunknown', max_length=100)),
                ('description', models.TextField(default='unknown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=100)),
                ('baseAsset', models.CharField(max_length=100)),
                ('baseAssetPrecision', models.IntegerField()),
                ('quoteAsset', models.CharField(max_length=100)),
                ('quotePrecision', models.IntegerField()),
                ('quoteAssetPrecision', models.IntegerField()),
                ('baseCommissionPrecision', models.IntegerField()),
                ('quoteCommissionPrecision', models.IntegerField()),
                ('orderTypes', models.JSONField()),
                ('icebergAllowed', models.BooleanField()),
                ('ocoAllowed', models.BooleanField()),
                ('otoAllowed', models.BooleanField()),
                ('quoteOrderQtyMarketAllowed', models.BooleanField()),
                ('allowTrailingStop', models.BooleanField()),
                ('cancelReplaceAllowed', models.BooleanField()),
                ('isSpotTradingAllowed', models.BooleanField()),
                ('isMarginTradingAllowed', models.BooleanField()),
                ('filters', models.JSONField(blank=True, null=True)),
                ('permissions', models.JSONField(blank=True, null=True)),
                ('permissionSets', models.JSONField(blank=True, null=True)),
                ('defaultSelfTradePreventionMode', models.CharField(max_length=100)),
                ('allowedSelfTradePreventionModes', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SymbolsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_new', models.IntegerField(default=0)),
                ('time_spent', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymbolError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbols_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_error', to='s_binance.symbolsinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('symbols', models.ManyToManyField(to='s_binance.symbol')),
            ],
        ),
    ]
