# Generated by Django 4.1.13 on 2024-07-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_binance', '0005_group_proxy_group_proxy_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='name',
            field=models.CharField(default='proxy', max_length=100),
        ),
    ]
