# Generated by Django 4.1.13 on 2024-07-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100, unique=True)),
                ('pair', models.CharField(max_length=100)),
                ('contractType', models.CharField(max_length=100)),
                ('deliveryDate', models.BigIntegerField()),
                ('onboardDate', models.BigIntegerField()),
                ('status', models.CharField(max_length=100)),
                ('maintMarginPercent', models.CharField(max_length=100)),
                ('requiredMarginPercent', models.CharField(max_length=100)),
                ('baseAsset', models.CharField(max_length=100)),
                ('quoteAsset', models.CharField(max_length=100)),
                ('marginAsset', models.CharField(max_length=100)),
                ('pricePrecision', models.IntegerField()),
                ('quantityPrecision', models.IntegerField()),
                ('baseAssetPrecision', models.IntegerField()),
                ('quotePrecision', models.IntegerField()),
                ('underlyingType', models.CharField(blank=True, max_length=100, null=True)),
                ('underlyingSubType', models.JSONField(blank=True, null=True)),
                ('settlePlan', models.IntegerField(blank=True, null=True)),
                ('triggerProtect', models.CharField(blank=True, max_length=100, null=True)),
                ('liquidationFee', models.CharField(blank=True, max_length=100, null=True)),
                ('marketTakeBound', models.CharField(blank=True, max_length=100, null=True)),
                ('maxMoveOrderLimit', models.IntegerField(blank=True, null=True)),
                ('orderTypes', models.JSONField(blank=True, null=True)),
                ('timeInForce', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymbolsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_new', models.IntegerField(default=0)),
                ('time_spent', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymbolError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbols_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_error', to='f_binance.symbolsinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('symbols', models.ManyToManyField(to='f_binance.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterType', models.CharField(max_length=100)),
                ('maxPrice', models.CharField(blank=True, max_length=100, null=True)),
                ('minPrice', models.CharField(blank=True, max_length=100, null=True)),
                ('tickSize', models.CharField(blank=True, max_length=100, null=True)),
                ('maxQty', models.CharField(blank=True, max_length=100, null=True)),
                ('minQty', models.CharField(blank=True, max_length=100, null=True)),
                ('stepSize', models.CharField(blank=True, max_length=100, null=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('notional', models.CharField(blank=True, max_length=100, null=True)),
                ('multiplierUp', models.CharField(blank=True, max_length=100, null=True)),
                ('multiplierDown', models.CharField(blank=True, max_length=100, null=True)),
                ('multiplierDecimal', models.IntegerField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='f_binance.symbol')),
            ],
        ),
    ]
