# Generated by Django 4.1.13 on 2024-07-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(max_length=100)),
                ('min_price', models.CharField(blank=True, max_length=100, null=True)),
                ('max_price', models.CharField(blank=True, max_length=100, null=True)),
                ('tick_size', models.CharField(blank=True, max_length=100, null=True)),
                ('step_size', models.CharField(blank=True, max_length=100, null=True)),
                ('min_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('max_qty', models.CharField(blank=True, max_length=100, null=True)),
                ('limit', models.CharField(blank=True, max_length=100, null=True)),
                ('notional', models.CharField(blank=True, max_length=100, null=True)),
                ('multiplier_up', models.CharField(blank=True, max_length=100, null=True)),
                ('multiplier_down', models.CharField(blank=True, max_length=100, null=True)),
                ('multiplier_decimal', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('pair', models.CharField(max_length=100)),
                ('contract_type', models.CharField(max_length=100)),
                ('delivery_date', models.BigIntegerField()),
                ('onboard_date', models.BigIntegerField()),
                ('status', models.CharField(max_length=100)),
                ('maint_margin_percent', models.CharField(max_length=100)),
                ('required_margin_percent', models.CharField(max_length=100)),
                ('base_asset', models.CharField(max_length=100)),
                ('quote_asset', models.CharField(max_length=100)),
                ('margin_asset', models.CharField(max_length=100)),
                ('price_precision', models.IntegerField()),
                ('quantity_precision', models.IntegerField()),
                ('base_asset_precision', models.IntegerField()),
                ('quote_precision', models.IntegerField()),
                ('order_types', models.JSONField()),
                ('time_in_force', models.JSONField()),
                ('filters', models.ManyToManyField(to='f_binance.filter')),
            ],
        ),
    ]
