# Generated by Django 4.1.13 on 2024-07-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_binance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='liquidation_fee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='market_take_bound',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='max_move_order_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='settle_plan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='trigger_protect',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='underlying_sub_type',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='underlying_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='symbol',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
