# Generated by Django 4.1.13 on 2024-07-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_binance', '0002_symbol_filters_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='nunknown', max_length=100)),
                ('description', models.TextField(default='unknown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
