# Generated by Django 4.1.13 on 2024-07-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_binance', '0004_proxy_group_proxy_active_group_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='name',
            field=models.CharField(default='proxy', max_length=100),
        ),
    ]
